### ISSUE TITLE
REGRESSION: Revert `manual_merge` to being `no` by default

### ISSUE THREAD

**Issue by akashivskyy** [bitrise-io/steps-git-clone#47]
The change introduced in version 3.6.0 is breaking _all_ builds from private repositories. I believe no such breaking change should take place in a step that is fundamental to all builds on Bitrise.

I'm kind of dissapointed and unhappy, as this breaks all 50+ private projects that my organization runs on Bitrise.

**Comment by viktorbenei** [comment]
Sorry for the issue @akashivskyy , we indeed should have make this clearer.

Could you please contact our support with the related build log(s)? We'll take a look asap and will make the step auto-detect when it have to change mode.

Right now, if you use private forks, you can set the old merge algorithm with the new `manual_merge` configuration (https://github.com/bitrise-io/steps-git-clone/blob/master/step.yml#L111). Simply set it to `no` and that restores the previous version's merge logic/algorithm.

We plan to release a new version ASAP which will be able to auto-detect when this change should be made, so that you don't have to set this configuration yourself.

Note: this is only an issue if you use **private forks**, at least we don't know about any other case when this would affect the checkout.

In any case, please send us the related build logs so that we can check it, and for now just switch the `manual_merge` to "no" to restore the previous logic, or simply downgrade the step to the previous, 3.5.x version.

Sorry for the inconvenience.

**Comment by viktorbenei** [comment]
Just updated our release notes with this note.

**Comment by viktorbenei** [comment]
We published v3.6.1 (https://github.com/bitrise-io/steps-git-clone/releases/tag/3.6.1) which will auto-detect if it has to fall back to the "service specific" implementation - which only affects github PRs from private forks.

But just to be sure we also pushed v3.6.2 which restores the previous merge strategy, the one used in v3.5.x (by setting `manual_merge` to `"no"` by default). The new merge strategy is now opt-in instead of opt-out while we're tracking down possible issues with the new PR merge strategy.

Thanks for reporting the issue @akashivskyy and once again we're terribly sorry for the inconvenience. We'll do our best to avoid this happening again.

I'll close this ticket for now, but if you'd still have the issue with 3.6.2 please let us know!
Happy Building!
